#!/bin/sh

# Cores
NC='\033[0m' # No Color
Blue='\033[1;34m'
Red='\033[1;31m'
Green='\033[1;32m'

CHANGED_FILES=$(git diff --cached --name-only) # Lista de arquivos alterados

if echo "$CHANGED_FILES" | grep -q "^web/"; then
  echo "${Green}Verificando o projeto 'web':${NC}" 
  cd web
  echo

  # Rodar o phpstan
  echo "${Blue}1. Rodando o PHPStan${NC}"
  ./vendor/bin/phpstan
  if [ $? -ne 0 ]; then
    echo "${Red} O PHPStan encontrou erros. ${NC}"
    exit 1
  fi

  # Rodar os teste
  echo "${Blue}2. Rodando o Testes em paralelo${NC}"
  php artisan test --parallel
  if [ $? -ne 0 ]; then
    echo "${Red} Tivemos erro em algum teste, revise o código ou o teste! ${NC}"
    exit 1
  fi

  # Formatar cada arquivo alterado usando o Laravel Pint
  STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".php\{0,1\}$" | sed 's|^web/||') || true

  echo "${Blue}3. Formatando os arquivos com o Laravel Pint${NC}"

  for FILE in $STAGED_FILES
  do
    ./vendor/bin/pint "${FILE}" > /dev/null >&1;
    git add "${FILE}"
  done
fi

# Verificando o projeto mobile
if echo "$CHANGED_FILES" | grep -q "^mobile/"; then
  echo
  echo "${Green}Verificando o projeto 'mobile':${NC}" 
  echo
  # Verifica se está na pasta web
    if [ "$(basename "$(pwd)")" = "web" ]; then
      cd ../mobile
    else
      cd mobile
    fi

  # Rodar o ESLint
  echo "${Blue}1. Rodando o ESLint${NC}"
  npm run lint
  if [ $? -ne 0 ]; then
    echo "${Red} O ESLint encontrou erros. ${NC}"
    exit 1
  fi

  # Rodar os testes
  echo "${Blue}2. Rodando o Testes em paralelo${NC}"
  npm run test
  if [ $? -ne 0 ]; then
    echo "${Red} Tivemos erro em algum teste, revise o código ou o teste! ${NC}"
    exit 1
  fi

  # Formatar cada arquivo alterado usando o Prettier
  STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.(js|jsx|ts|tsx)$" | sed 's|^mobile/||') || true

  echo "${Blue}3. Formatando os arquivos com o Prettier${NC}"

  for FILE in $STAGED_FILES
  do
    npx prettier --write "${FILE}" > /dev/null >&1;
    git add "${FILE}"
  done
fi